### ISSUE TITLE
error on path

### ISSUE THREAD

**Issue by ayazzali** [naqvitalha/rn-rnw-setup-live-reload#3]
your project is doing well. But i had problem with my exist project:
after instruction I had to 
-- npm i webpack-cli -D
and then

**Comment by ayazzali** [comment]
here

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ayaz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rn-rnw-setup-live-reload@1.0.0~prestart: rn-rnw-setup-live-reload@1.0.0
6 info lifecycle rn-rnw-setup-live-reload@1.0.0~start: rn-rnw-setup-live-reload@1.0.0
7 verbose lifecycle rn-rnw-setup-live-reload@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle rn-rnw-setup-live-reload@1.0.0~start: PATH: C:\Users\Ayaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ayaz\source\repos\newreactnative\qqq\rn-rnw-setup-live-reload\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\platform-tools;C:\Users\Ayaz\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle rn-rnw-setup-live-reload@1.0.0~start: CWD: C:\Users\Ayaz\source\repos\newreactnative\qqq\rn-rnw-setup-live-reload
10 silly lifecycle rn-rnw-setup-live-reload@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --watch -port 8082' ]
11 silly lifecycle rn-rnw-setup-live-reload@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle rn-rnw-setup-live-reload@1.0.0~start: Failed to exec start script
13 verbose stack Error: rn-rnw-setup-live-reload@1.0.0 start: `webpack-dev-server --watch -port 8082`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Ayaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Ayaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rn-rnw-setup-live-reload@1.0.0
15 verbose cwd C:\Users\Ayaz\source\repos\newreactnative\qqq\rn-rnw-setup-live-reload
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ayaz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error rn-rnw-setup-live-reload@1.0.0 start: `webpack-dev-server --watch -port 8082`
22 error Exit status 1
23 error Failed at the rn-rnw-setup-live-reload@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

>
